### ISSUE TITLE
Incorrect total count for crime location visualization

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/events-tracker#10]
The total count of the events is incorrect for crime location visualization.

![image](https://user-images.githubusercontent.com/19175505/146551271-d8c5f069-3a99-498d-978c-ec167a434094.png)

how to reproduce:

- open the denver example
- select Robbey category
- change the map visualization to Crime Location Map
- click on a circle on the map

current:

- legend shows wrong max min symbol
- popup show wrong total count

expected:
- legend shows correct max min symbol based on all the features visible on map
- popup show correct total count based on selected categories

**Comment by tonym3nsa** [comment]
@mbarto I can't seem to find the min/max legend you are referring to in the story. Could you please outline it for me

**Comment by allyoucanmap** [comment]
![image](https://user-images.githubusercontent.com/19175505/149769361-74c12fe4-3fe2-4aa3-90ac-8a723d69f502.png)

@tonym3nsa this select input allows you to change map visualization
