### ISSUE TITLE
Improve the UX/UI of counters

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/events-tracker#7]
We should improve the UI of the counters to make more visible the fact that they are selectable

current UI
![image](https://user-images.githubusercontent.com/19175505/146527124-45cb98a1-7a78-44d5-992e-4cd420b210fe.png)

![image](https://user-images.githubusercontent.com/19175505/146527173-14805d14-855f-4b02-885f-32c6a7517cad.png)

We need some mockup before proceed.

**Comment by tonym3nsa** [comment]
@allyoucanmap Here's the proposed design of the updated counter card

![Artboard 1@2x](https://user-images.githubusercontent.com/1873416/150785000-ac3de680-aad4-406b-9f02-998c923b48a5.jpg)

**Comment by allyoucanmap** [comment]
@tonym3nsa I like the idea. Could we test also with the selection color on hover instead of the color of the border?
I'm worried that too many different colors on hover could be confusing (but maybe not)

**Comment by tonym3nsa** [comment]
@allyoucanmap here's with the selection color as the background. 

![Artboard -alt@2x](https://user-images.githubusercontent.com/1873416/150788539-a803504f-bfce-403a-a939-74f611067c46.jpg)

**Comment by allyoucanmap** [comment]
@tonym3nsa we could also keep the border color to have reference to the specific category. probably this approach needs a slightly different blue
![image](https://user-images.githubusercontent.com/19175505/150789302-9ac8a62c-6ca9-4d08-9805-87609db5df5b.png)
